server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basic-framework?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
